# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Branches
branches:
  only:
  - master

# Use new container infrastructure to enable caching
sudo: false

# We set python as language to make use of travis virtualenv
language: python
python:
  - "3.6"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- pip install -r $TRAVIS_BUILD_DIR/webscrap/requirements.txt
- python $TRAVIS_BUILD_DIR/webscrap/ds_weapons_webscrap.py ${WEAPONS_JSON}
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package and run it
- stack --no-terminal build --no-haddock --no-haddock-deps
- stack --no-terminal exec ds-weapons-api-exe --no-haddock --no-haddock-deps -- ${WEAPONS_JSON}

after_success:
# Deploy to gh-pages
- bash ./scripts/deploy.sh

# Environment
env:
  global:
  - WEAPONS_JSON: weapons.json
  - GH_USER: jgalat
  - GH_REPO: ds-weapons-api
  - secure: jEcZGCDnK83vo1Gtf5tHP6enKQ5ZnIYGrixjlDrbKjBNIQwlsvr2vt1fVWDU4bzzDms2ucCR3Ql8SWaZii9Vl8axoQvC2HWkmRSo8thri7WRTAN2DLFrERQfjxpVBXm873i5GXHDBy+rlG0VVQBQ7Ukqd+TB9DyuZ8fubRMiPIY7xDCETAQMlF+pO9dAN3xGxPnCdl1qi0hE0FqQiNJ80jNWLONxLdiHhtgHz9Ejql9cdf9ZmznEW84N46yS1tfkeMn0FZjqydwx/vrudoSMKj+t3uG8p1WhShLoKbr4JGdzhwHW5FtDUyCbqqQfAT2XyVHG3CUs413qmLuiad8yq5RDJWbuBlnZ22ZHRvmVSwqt0gcmOPCzO0+4dYBwLdRAk09FtjqYmHs8Swkbvn5nN0h1blqgMesGTeGKaJ96MQdqOdePMSInUhy8f+scRZITNl/f628GoQrZihQIrWUb5z4dlaP5BuLouj7C+nGpHX47e448ITvPBGvNKizBO3N0IWgoeYnp0JeOGw9ZVnP3BXaupqxd8qioNpJbvTbqpfU+Wemuu1F3JGkC/GsVMmgLIwAR6aa2tQjlJLXGY08ldZZ4ZS7J574BBKwEd2FWU0WwSrlP1bkDrDAGn0qSoBKKT9GarLj5G8iyeBaUG+oSqHgy31o10qGo4wZI2xixfms=
